# Generated by Django 2.2.5 on 2019-10-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=123444, max_length=255),
            preserve_default=False,
        ),
    ]
