# Generated by Django 2.2.5 on 2019-10-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
