# Generated by Django 2.2.5 on 2019-10-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_user_salt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
