# Generated by Django 2.2.5 on 2019-10-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('areas', models.ManyToManyField(to='database.Areas')),
                ('cities', models.ManyToManyField(to='database.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('areas', models.ManyToManyField(to='database.Areas')),
                ('cities', models.ManyToManyField(to='database.Cities')),
                ('languages', models.ManyToManyField(to='database.Languages')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Events')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='languages',
            field=models.ManyToManyField(to='database.Languages'),
        ),
    ]
