# Generated by Django 2.2.5 on 2019-12-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='theme',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
