# Generated by Django 2.2.5 on 2019-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='areas',
            field=models.ManyToManyField(related_name='ClientAreas', to='database.Areas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cities',
            field=models.ManyToManyField(related_name='ClientCities', to='database.Cities'),
        ),
        migrations.AlterField(
            model_name='client',
            name='languages',
            field=models.ManyToManyField(related_name='ClientLanguages', to='database.Languages'),
        ),
    ]
