# Generated by Django 2.2.5 on 2019-10-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191030_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Languages')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cities')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Areas')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Client')),
            ],
        ),
    ]
