# Generated by Django 2.2.5 on 2019-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_clientareas_clientcities_clientlanguages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='client',
            name='languages',
        ),
    ]
